const orderFoodTest = require('./orderFood');


describe('Coding Meetup #14 - Higher-Order Functions Series - Order the food', () => {

    it('Test_1', () => {
        expect(orderFoodTest(list1)).toEqual({ vegetarian: 2, standard: 1, vegan: 1 } );
    });

    it('Test_2', () => {
        expect(orderFoodTest(list2)).
        toEqual({"diabetic": 1, "gluten-intolerant": 3, "standard": 3, "vegan": 8, "vegetarian": 5 } );
    });

    it('Test_3', () => {
        expect(orderFoodTest(list3))
            .toEqual({ "diabetic": 5, "gluten-intolerant": 3, "standard": 5, "vegan": 1, "vegetarian": 6  } );
    });

    it('Test_4', () => {
        expect(orderFoodTest(list4))
            .toEqual({ "diabetic": 6, "gluten-intolerant": 5, "standard": 4, "vegan": 2, "vegetarian": 3, } );
    });

    it('Test_5', () => {
        expect(orderFoodTest(list5))
            .toEqual({ "diabetic": 4, "gluten-intolerant": 3, "standard": 4, "vegan": 3, "vegetarian": 6, } );
    });
});

let  list1 = [
    { firstName: 'Noah', lastName: 'M.', country: 'Switzerland', continent: 'Europe', age: 19, language: 'C',
        meal: 'vegetarian' },
    { firstName: 'Anna', lastName: 'R.', country: 'Liechtenstein', continent: 'Europe', age: 52, language: 'JavaScript',
        meal: 'standard' },
    { firstName: 'Ramona', lastName: 'R.', country: 'Paraguay', continent: 'Americas', age: 29, language: 'Ruby',
        meal: 'vegan' },
    { firstName: 'George', lastName: 'B.', country: 'England', continent: 'Europe', age: 81, language: 'C',
        meal: 'vegetarian' },
];

let  list2 = [
    { firstName: 'Liam', lastName: 'D.', country: 'Faroe Islands', continent: 'Europe', age: 28, language: 'Python',
        meal: 'gluten-intolerant' },
    { firstName: 'Nor', lastName: 'E.', country: 'Malaysia', continent: 'Asia', age: 21, language: 'Clojure',
        meal: 'vegan' },
    { firstName: 'Nareh', lastName: 'Q.', country: 'Armenia', continent: 'Europe', age: 30, language: 'Clojure',
        meal: 'standard' },
    { firstName: 'Amar', lastName: 'V.', country: 'Bosnia and Herzegovina', continent: 'Europe', age: 32, language: 'Ruby',
        meal: 'vegetarian' },
    { firstName: 'Noah', lastName: 'M.', country: 'Switzerland', continent: 'Europe', age: 19, language: 'C',
        meal: 'standard' },
    { firstName: 'Sofia', lastName: 'W.', country: 'Moldova', continent: 'Europe', age: 29, language: 'Ruby',
        meal: 'vegetarian' },
    { firstName: 'Gabriel', lastName: 'X.', country: 'Monaco', continent: 'Europe', age: 29, language: 'PHP',
        meal: 'diabetic' },
    { firstName: 'Mehdi', lastName: 'H.', country: 'Tunisia', continent: 'Africa', age: 42, language: 'Python',
        meal: 'vegetarian' },
    { firstName: 'Mark', lastName: 'G.', country: 'Scotland', continent: 'Europe', age: 22, language: 'JavaScript',
        meal: 'vegan' },
    { firstName: 'Mohammad', lastName: 'N.', country: 'United Arab Emirates', continent: 'Asia', age: 39, language: 'C',
        meal: 'vegan' },
    { firstName: 'Krishna', lastName: 'G.', country: 'Nepal', continent: 'Asia', age: 22, language: 'Java',
        meal: 'vegan' },
    { firstName: 'Rimas', lastName: 'C.', country: 'Jordan', continent: 'Asia', age: 44, language: 'Java',
        meal: 'vegan' },
    { firstName: 'Madison', lastName: 'U.', country: 'United States', continent: 'Americas', age: 32, language: 'Ruby',
        meal: 'vegetarian' },
    { firstName: 'Odval', lastName: 'F.', country: 'Mongolia', continent: 'Asia', age: 38, language: 'Python',
        meal: 'vegan' },
    { firstName: 'George', lastName: 'B.', country: 'England', continent: 'Europe', age: 21, language: 'C',
        meal: 'gluten-intolerant' },
    { firstName: 'Mariami', lastName: 'G.', country: 'Georgia', continent: 'Europe', age: 29, language: 'Python',
        meal: 'standard' },
    { firstName: 'Mia', lastName: 'H.', country: 'Germany', continent: 'Europe', age: 39, language: 'Ruby',
        meal: 'vegan' },
    { firstName: 'Lukas', lastName: 'R.', country: 'Austria', continent: 'Europe', age: 89, language: 'C',
        meal: 'vegan' },
    { firstName: 'Oliver', lastName: 'P.', country: 'Wales', continent: 'Europe', age: 29, language: 'JavaScript',
        meal: 'vegetarian' },
    { firstName: 'Sofia', lastName: 'P.', country: 'Italy', continent: 'Europe', age: 41, language: 'Clojure',
        meal: 'gluten-intolerant' }
];

let  list3 = [
    { firstName: 'Luka', lastName: 'J.', country: 'Slovenia', continent: 'Europe', age: 29, language: 'Clojure',
        meal: 'vegetarian' },
    { firstName: 'Krishna', lastName: 'G.', country: 'Nepal', continent: 'Asia', age: 22, language: 'Java',
        meal: 'vegan' },
    { firstName: 'Viktoria', lastName: 'W.', country: 'Bulgaria', continent: 'Europe', age: 28, language: 'PHP',
        meal: 'gluten-intolerant' },
    { firstName: 'Emily', lastName: 'A.', country: 'Northern Ireland', continent: 'Europe', age: 32, language: 'JavaScript',
        meal: 'standard' },
    { firstName: 'Thomas', lastName: 'L.', country: 'Canada', continent: 'Americas', age: 38, language: 'Java',
        meal: 'standard' },
    { firstName: 'Aya', lastName: 'D.', country: 'Libya', continent: 'Africa', age: 39, language: 'C',
        meal: 'vegetarian' },
    { firstName: 'Victoria', lastName: 'T.', country: 'Puerto Rico', continent: 'Americas', age: 30, language: 'Python',
        meal: 'vegetarian' },
    { firstName: 'Maria', lastName: 'S.', country: 'Peru', continent: 'Americas', age: 30, language: 'C',
        meal: 'standard' },
    { firstName: 'Noah', lastName: 'M.', country: 'Switzerland', continent: 'Europe', age: 19, language: 'C',
        meal: 'standard' },
    { firstName: 'Althea', lastName: 'I.', country: 'Philippines', continent: 'Asia', age: 31, language: 'Python',
        meal: 'diabetic' },
    { firstName: 'Mehdi', lastName: 'H.', country: 'Tunisia', continent: 'Africa', age: 42, language: 'Python',
        meal: 'vegetarian' },
    { firstName: 'George', lastName: 'B.', country: 'England', continent: 'Europe', age: 21, language: 'C',
        meal: 'gluten-intolerant' },
    { firstName: 'Joao', lastName: 'D.', country: 'Portugal', continent: 'Europe', age: 35, language: 'JavaScript',
        meal: 'diabetic' },
    { firstName: 'Fatima', lastName: 'H.', country: 'Pakistan', continent: 'Asia', age: 28, language: 'JavaScript',
        meal: 'standard' },
    { firstName: 'Seoyeon', lastName: 'J.', country: 'South Korea', continent: 'Asia', age: 29, language: 'Ruby',
        meal: 'vegetarian' },
    { firstName: 'Emma', lastName: 'U.', country: 'Belgium', continent: 'Europe', age: 39, language: 'Python',
        meal: 'gluten-intolerant' },
    { firstName: 'Yusuf', lastName: 'N.', country: 'Turkey', continent: 'Europe', age: 22, language: 'Python',
        meal: 'diabetic' },
    { firstName: 'Anna', lastName: 'R.', country: 'Liechtenstein', continent: 'Europe', age: 32, language: 'JavaScript',
        meal: 'diabetic' },
    { firstName: 'Kseniya', lastName: 'T.', country: 'Belarus', continent: 'Europe', age: 29, language: 'JavaScript',
        meal: 'diabetic' },
    { firstName: 'Yerasyl', lastName: 'D.', country: 'Kazakhstan', continent: 'Asia', age: 22, language: 'Ruby',
        meal: 'vegetarian' }
];

let list4 = [ { firstName: 'Laia',
    lastName: 'P.',
    country: 'Andorra',
    continent: 'Europe',
    age: 55,
    language: 'Ruby',
    meal: 'standard' },
    { firstName: 'Sofia',
        lastName: 'I.',
        country: 'Argentina',
        continent: 'Americas',
        age: 35,
        language: 'Java',
        meal: 'vegan' },
    { firstName: 'Oliver',
        lastName: 'P.',
        country: 'Wales',
        continent: 'Europe',
        age: 29,
        language: 'JavaScript',
        meal: 'vegetarian' },
    { firstName: 'Nikola',
        lastName: 'H.',
        country: 'Serbia',
        continent: 'Europe',
        age: 29,
        language: 'Python',
        meal: 'standard' },
    { firstName: 'Oliver',
        lastName: 'Q.',
        country: 'Australia',
        continent: 'Oceania',
        age: 19,
        language: 'PHP',
        meal: 'gluten-intolerant' },
    { firstName: 'Nikau',
        lastName: 'R.',
        country: 'New Zealand',
        continent: 'Oceania',
        age: 39,
        language: 'Ruby',
        meal: 'diabetic' },
    { firstName: 'Althea',
        lastName: 'I.',
        country: 'Philippines',
        continent: 'Asia',
        age: 31,
        language: 'Python',
        meal: 'diabetic' },
    { firstName: 'Aadya',
        lastName: 'Y.',
        country: 'India',
        continent: 'Asia',
        age: 29,
        language: 'PHP',
        meal: 'vegetarian' },
    { firstName: 'Jakub',
        lastName: 'Z.',
        country: 'Czech Republic',
        continent: 'Europe',
        age: 42,
        language: 'Java',
        meal: 'gluten-intolerant' },
    { firstName: 'Emma',
        lastName: 'U.',
        country: 'Belgium',
        continent: 'Europe',
        age: 39,
        language: 'Python',
        meal: 'gluten-intolerant' },
    { firstName: 'Alexander',
        lastName: 'F.',
        country: 'Russia',
        continent: 'Europe',
        age: 89,
        language: 'Java',
        meal: 'gluten-intolerant' },
    { firstName: 'Piotr',
        lastName: 'B.',
        country: 'Poland',
        continent: 'Europe',
        age: 128,
        language: 'JavaScript',
        meal: 'standard' },
    { firstName: 'Emily',
        lastName: 'N.',
        country: 'Ireland',
        continent: 'Europe',
        age: 38,
        language: 'Ruby',
        meal: 'vegan' },
    { firstName: 'Liam',
        lastName: 'D.',
        country: 'Faroe Islands',
        continent: 'Europe',
        age: 28,
        language: 'Python',
        meal: 'gluten-intolerant' },
    { firstName: 'Emilija',
        lastName: 'S.',
        country: 'Lithuania',
        continent: 'Europe',
        age: 19,
        language: 'Python',
        meal: 'vegetarian' },
    { firstName: 'Jayden',
        lastName: 'P.',
        country: 'Jamaica',
        continent: 'Americas',
        age: 42,
        language: 'JavaScript',
        meal: 'diabetic' },
    { firstName: 'Emma',
        lastName: 'B.',
        country: 'Norway',
        continent: 'Europe',
        age: 19,
        language: 'Clojure',
        meal: 'diabetic' },
    { firstName: 'Daniel',
        lastName: 'J.',
        country: 'Aruba',
        continent: 'Americas',
        age: 42,
        language: 'JavaScript',
        meal: 'standard' },
    { firstName: 'Emma',
        lastName: 'Z.',
        country: 'Netherlands',
        continent: 'Europe',
        age: 29,
        language: 'Ruby',
        meal: 'diabetic' },
    { firstName: 'Noa',
        lastName: 'A.',
        country: 'Israel',
        continent: 'Asia',
        age: 40,
        language: 'Ruby',
        meal: 'diabetic' }
];

let  list5 = [ { firstName: 'Laia',
    lastName: 'P.',
    country: 'Andorra',
    continent: 'Europe',
    age: 55,
    language: 'Ruby',
    meal: 'standard' },
    { firstName: 'Jakub',
        lastName: 'Z.',
        country: 'Czech Republic',
        continent: 'Europe',
        age: 42,
        language: 'Java',
        meal: 'gluten-intolerant' },
    { firstName: 'Viktoria',
        lastName: 'W.',
        country: 'Bulgaria',
        continent: 'Europe',
        age: 28,
        language: 'PHP',
        meal: 'gluten-intolerant' },
    { firstName: 'Fatemeh',
        lastName: 'Z.',
        country: 'Iran',
        continent: 'Asia',
        age: 29,
        language: 'Java',
        meal: 'vegan' },
    { firstName: 'Jing',
        lastName: 'X.',
        country: 'China',
        continent: 'Asia',
        age: 39,
        language: 'Ruby',
        meal: 'vegetarian' },
    { firstName: 'Aadya',
        lastName: 'Y.',
        country: 'India',
        continent: 'Asia',
        age: 29,
        language: 'PHP',
        meal: 'vegetarian' },
    { firstName: 'Piotr',
        lastName: 'B.',
        country: 'Poland',
        continent: 'Europe',
        age: 128,
        language: 'JavaScript',
        meal: 'standard' },
    { firstName: 'Mark',
        lastName: 'G.',
        country: 'Scotland',
        continent: 'Europe',
        age: 22,
        language: 'JavaScript',
        meal: 'vegan' },
    { firstName: 'Liam',
        lastName: 'D.',
        country: 'Faroe Islands',
        continent: 'Europe',
        age: 28,
        language: 'Python',
        meal: 'gluten-intolerant' },
    { firstName: 'Manuel',
        lastName: 'C.',
        country: 'Equatorial Guinea',
        continent: 'Africa',
        age: 22,
        language: 'Ruby',
        meal: 'vegetarian' },
    { firstName: 'Agustin',
        lastName: 'M.',
        country: 'Chile',
        continent: 'Americas',
        age: 37,
        language: 'C',
        meal: 'vegetarian' },
    { firstName: 'Sara',
        lastName: 'Y.',
        country: 'Montenegro',
        continent: 'Europe',
        age: 39,
        language: 'C',
        meal: 'diabetic' },
    { firstName: 'Mariami',
        lastName: 'G.',
        country: 'Georgia',
        continent: 'Europe',
        age: 29,
        language: 'Python',
        meal: 'standard' },
    { firstName: 'Emma',
        lastName: 'Z.',
        country: 'Netherlands',
        continent: 'Europe',
        age: 29,
        language: 'Ruby',
        meal: 'diabetic' },
    { firstName: 'Fatima',
        lastName: 'H.',
        country: 'Pakistan',
        continent: 'Asia',
        age: 28,
        language: 'JavaScript',
        meal: 'standard' },
    { firstName: 'Sofia',
        lastName: 'C.',
        country: 'Estonia',
        continent: 'Europe',
        age: 29,
        language: 'PHP',
        meal: 'vegetarian' },
    { firstName: 'Ramon',
        lastName: 'R.',
        country: 'Paraguay',
        continent: 'Americas',
        age: 29,
        language: 'Ruby',
        meal: 'diabetic' },
    { firstName: 'Nor',
        lastName: 'E.',
        country: 'Malaysia',
        continent: 'Asia',
        age: 21,
        language: 'Clojure',
        meal: 'vegan' },
    { firstName: 'Althea',
        lastName: 'I.',
        country: 'Philippines',
        continent: 'Asia',
        age: 31,
        language: 'Python',
        meal: 'diabetic' },
    { firstName: 'Sofia',
        lastName: 'W.',
        country: 'Moldova',
        continent: 'Europe',
        age: 29,
        language: 'Ruby',
        meal: 'vegetarian' }
];